version: 0.2
env:
  variables:
    IMAGE_REPO_NAME: udacity-project3
    BUILD-NUMBER: latest
    AWS_ACCOUNT_ID: 628127659257
    AWS_DEFAULT_REGION: us-east-1
phases:
  pre_build:
    commands:
      - echo Logging into ECR
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
  build:
    commands:
      - echo Starting build at `date`
      - echo Building the Docker image...
      - docker build -t $IMAGE_REPO_NAME:$BUILD-NUMBER ./analytics/.
      - docker tag $IMAGE_REPO_NAME:$BUILD-NUMBER $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$BUILD-NUMBER
  post_build:
    commands:
      - echo Completed build at `date`
      - echo Pushing the Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$BUILD-NUMBER
